version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env
    networks:
      - my_network
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

  redis:
    image: redis:latest
    container_name: rdb
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my_network


  mongodb:
    image: mongo:latest
    container_name: mdb
    ports:
      - 27017:27017
    
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - my_network
    restart: always
  
volumes:
  mongodb_data: 
  rabbitmq_data:
  rabbitmq_logs: 
  mongodb_config:

networks:
  my_network:
    driver: bridge
    